import { createHash } from 'node:crypto';
import { describe,expect,it } from 'vitest';
import { buildApp } from '../src/app.js';
import { createSource } from '../src/data/source.js';
import { SpecContestRepository } from '../src/contest/spec-repository.js';
import { MemoryContestBrochureStore } from '../src/contest/brochure-store.js';

process.env.MONGODB_URI='';
const source=await createSource();
const H=(extra:Record<string,string>={})=>({'x-agent-id':'A1001','x-tenant':'MY',...extra});
const baseConfiguration={basics:{code:'HIST2025'},audience:{codes:['PERSONAL']},qualification:{routes:[],tiers:[],periods:[],targets:[],rewardPrecedenceCode:'HIGHEST_ONLY'},calculation:{metric:'TPC'},rewards:{tiers:[]},governance:{stages:[]}};
const checksum=createHash('sha256').update(JSON.stringify(baseConfiguration)).digest('hex');
const seed=(status:'COMPLETED'|'CANCELLED'|'ARCHIVED'|'DRAFT'='COMPLETED')=>[{contest:{contestId:'contest_historic_2025',code:'HIST2025',nameKey:'contest.historic',country:'MY',timezone:'Asia/Kuala_Lumpur',ownerRef:'A1001',status,latestVersionId:'version_historic_2025_v1',publishedVersionId:'version_historic_2025_v1',archived:status==='ARCHIVED',revision:3,campaignStart:'2025-01-01',campaignEnd:'2025-12-31',audienceCodes:['PERSONAL'],ruleCount:1,createdAt:'2025-01-01T00:00:00Z',updatedAt:'2026-01-31T00:00:00Z'},version:{versionId:'version_historic_2025_v1',contestId:'contest_historic_2025',revision:1,displayVersion:'1.0',status:status==='DRAFT'?'DRAFT':'PUBLISHED',configuration:baseConfiguration,checksum,createdBy:'A1001',createdAt:'2025-01-01T00:00:00Z'}}];
const app=(status:Parameters<typeof seed>[0]='COMPLETED')=>buildApp(source,new SpecContestRepository(undefined,seed(status)),new MemoryContestBrochureStore());
const command=(key:string,revision:number)=>H({'idempotency-key':key,'if-match':`"${revision}"`});

function multipart(fileName:string,mime:string,bytes:Buffer){const boundary='----pruaction-test-boundary';return{boundary,payload:Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="${fileName}"\r\nContent-Type: ${mime}\r\n\r\n`),bytes,Buffer.from(`\r\n--${boundary}--\r\n`)])};}

describe('historic contest and brochure API v0.3',()=>{
  it('lists historic contests and removes legacy templates',async()=>{const server=app();const list=await server.inject({url:'/contests/v1/historic-contests',headers:H()});expect(list.statusCode).toBe(200);expect(list.json().items).toEqual([expect.objectContaining({code:'HIST2025',status:'COMPLETED',actions:expect.arrayContaining(['ARCHIVE','REACTIVATE'])})]);expect((await server.inject({url:'/contests/v1/templates',headers:H()})).statusCode).toBe(404);});

  it('archives softly with guards and preserves the immutable version',async()=>{const server=app();const archived=await server.inject({method:'DELETE',url:'/contests/v1/contests/contest_historic_2025',headers:command('archive-historic-001',3)});expect(archived.statusCode).toBe(200);expect(archived.json()).toMatchObject({status:'ARCHIVED',archived:true,revision:4});const version=await server.inject({url:'/contests/v1/contest-versions/version_historic_2025_v1',headers:H()});expect(version.statusCode).toBe(200);expect(version.json()).toMatchObject({status:'PUBLISHED',checksum});const denied=await app('DRAFT').inject({method:'DELETE',url:'/contests/v1/contests/contest_historic_2025',headers:command('archive-draft-0001',3)});expect(denied.statusCode).toBe(409);});

  it('reactivates by cloning a historic version into a new draft',async()=>{const server=app('ARCHIVED');const response=await server.inject({method:'POST',url:'/contests/v1/contests/contest_historic_2025/reactivations',headers:command('reactivate-historic-001',3),payload:{baseVersionId:'version_historic_2025_v1',changeRationale:'Run a new cycle'}});expect(response.statusCode).toBe(201);expect(response.json()).toMatchObject({status:'DRAFT',baseVersionId:'version_historic_2025_v1',baseChecksum:checksum});expect(response.json().versionId).not.toBe('version_historic_2025_v1');const base=await server.inject({url:'/contests/v1/contest-versions/version_historic_2025_v1',headers:H()});expect(base.json()).toMatchObject({status:'PUBLISHED',checksum});});

  it('uploads and streams a valid PDF and rejects invalid content',async()=>{const server=app('DRAFT');const pdf=Buffer.from('%PDF-1.7\ncontest brochure\n%%EOF');const form=multipart('brochure.pdf','application/pdf',pdf);const uploaded=await server.inject({method:'PUT',url:'/contests/v1/contest-versions/version_historic_2025_v1/brochure',headers:{...command('upload-brochure-0001',1),'content-type':`multipart/form-data; boundary=${form.boundary}`},payload:form.payload});expect(uploaded.statusCode).toBe(201);expect(uploaded.json()).toMatchObject({fileName:'brochure.pdf',mediaType:'application/pdf',sizeBytes:pdf.length,status:'AVAILABLE',sha256:createHash('sha256').update(pdf).digest('hex')});const download=await server.inject({url:'/contests/v1/contest-versions/version_historic_2025_v1/brochure',headers:H()});expect(download.statusCode).toBe(200);expect(download.headers['content-type']).toContain('application/pdf');expect(download.rawPayload).toEqual(pdf);const bad=multipart('bad.pdf','application/pdf',Buffer.from('not a pdf'));const rejected=await app('DRAFT').inject({method:'PUT',url:'/contests/v1/contest-versions/version_historic_2025_v1/brochure',headers:{...command('upload-brochure-bad1',1),'content-type':`multipart/form-data; boundary=${bad.boundary}`},payload:bad.payload});expect(rejected.statusCode).toBe(422);});

  it('accepts exactly 10 MiB and rejects 10 MiB plus one byte',async()=>{const prior=process.env.CONTEST_BROCHURE_MAX_BYTES;process.env.CONTEST_BROCHURE_MAX_BYTES='99999999';try{const exact=Buffer.alloc(10_485_760);exact.write('%PDF-1.7\n');const acceptedForm=multipart('ten-mib.pdf','application/pdf',exact);const accepted=await app('DRAFT').inject({method:'PUT',url:'/contests/v1/contest-versions/version_historic_2025_v1/brochure',headers:{...command('upload-ten-mib-0001',1),'content-type':`multipart/form-data; boundary=${acceptedForm.boundary}`},payload:acceptedForm.payload});expect(accepted.statusCode).toBe(201);expect(accepted.json().sizeBytes).toBe(10_485_760);const oversized=Buffer.alloc(10_485_761);oversized.write('%PDF-1.7\n');const rejectedForm=multipart('over-ten-mib.pdf','application/pdf',oversized);const rejected=await app('DRAFT').inject({method:'PUT',url:'/contests/v1/contest-versions/version_historic_2025_v1/brochure',headers:{...command('upload-over-mib-01',1),'content-type':`multipart/form-data; boundary=${rejectedForm.boundary}`},payload:rejectedForm.payload});expect(rejected.statusCode).toBe(413);expect(rejected.json().code).toBe('CON-4131');}finally{if(prior===undefined)delete process.env.CONTEST_BROCHURE_MAX_BYTES;else process.env.CONTEST_BROCHURE_MAX_BYTES=prior;}});
});