import { createHash, randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import type { Document } from 'mongodb';
import type { SpecContestRepository, SpecActor } from './spec-repository.js';
import { DevelopmentHeaderPrincipalAdapter, type ContestPrincipalAdapter } from './principal.js';
import type { ContestBrochureStore } from './brochure-store.js';
import type { ContestBrochureImportService } from './brochure-import.js';
import { contestBrochureMaxBytes } from './brochure-limits.js';

const PREFIX = '/contests/v1';
const params = (properties: Document, required: string[]) => ({ type: 'object', properties, required, additionalProperties: false });
const idParams = (name: string) => params({ [name]: { type: 'string', minLength: 8, maxLength: 64 } }, [name]);
const body = { type: 'object', additionalProperties: true } as const;
function problem(reply: FastifyReply, status: number, code: string, title: string, detail?: string) { return reply.status(status).type('application/problem+json').send({ type: `urn:pruaction:contests:${code}`, title, status, code, traceId: randomUUID(), ...(detail ? { detail } : {}) }); }
const principalAdapters = new WeakMap<FastifyInstance, ContestPrincipalAdapter>();
function actor(req: FastifyRequest, reply: FastifyReply): SpecActor | undefined { const tenant = String(req.headers['x-tenant'] ?? ''); const route = req.routeOptions.url ?? req.url.split('?')[0]!; const requiredScopes = routeScopes(req.method, route); const adapter = principalAdapters.get(req.server) ?? new DevelopmentHeaderPrincipalAdapter(); const result = adapter.authorize(req, { tenant, requiredScopes, scopeMode: route === `${PREFIX}/approvals/:approvalId/decisions` ? 'ANY' : 'ALL', entityId: String(req.headers['x-entity-id'] ?? '') || undefined, channelCode: String(req.headers['x-channel-code'] ?? '') || undefined }); if (!result.allowed) { void problem(reply, result.status, result.code, result.title); return; } return result.actor; }
function command(req: FastifyRequest, reply: FastifyReply, needMatch = false): { actor: SpecActor; key: string; revision?: number } | undefined { const who = actor(req, reply); if (!who) return; const key = String(req.headers['idempotency-key'] ?? ''); if (key.length < 8) { void problem(reply, 400, 'CON-4001', 'Idempotency-Key is required'); return; } if (!needMatch) return { actor: who, key }; const match = /^"?(\d+)"?$/.exec(String(req.headers['if-match'] ?? '')); if (!match) { void problem(reply, 412, 'CON-4121', 'If-Match must contain the current revision'); return; } return { actor: who, key, revision: Number(match[1]) }; }
async function idempotent<T>(repository: SpecContestRepository, reply: FastifyReply, cmd: { actor: SpecActor; key: string }, operationId: string, input: unknown, action: () => Promise<T>): Promise<T | undefined> { const result = await repository.idempotent(cmd.actor.tenant, operationId, cmd.key, input, action); if (result.kind === 'CONFLICT') { void problem(reply, 409, 'CON-4091', 'Idempotency key was reused with a different request'); return; } if (result.kind === 'IN_PROGRESS') { void problem(reply, 409, 'CON-4092', 'The original command is still in progress'); return; } if (result.replay) reply.header('idempotent-replay', 'true'); return result.value; }

function routeScopes(method: string, route: string): readonly string[] {
  if (route === `${PREFIX}/approvals/:approvalId/decisions`) return ['contests:approve:business', 'contests:approve:compensation', 'contests:approve:risk'];
  if (route === `${PREFIX}/contest-versions/:versionId/submit`) return ['contests:submit'];
  if (route === `${PREFIX}/contest-versions/:versionId/publish`) return ['contests:publish'];
  if (route === `${PREFIX}/contests/:contestId` && method === 'DELETE' || route.includes('/reactivations')) return ['contests:historic:write'];
  if (route.includes('/brochure') && method === 'PUT') return ['contests:brochures:write'];
  if (route === `${PREFIX}/contest-imports` && method === 'POST') return ['contests:imports:write'];
  if (route.includes('/simulations')) return ['contests:simulate'];
  if (route.includes('/calculation-runs') || route === `${PREFIX}/source-snapshots`) return ['contests:runs:operate'];
  if (route === `${PREFIX}/audit-events`) return ['contests:audit:read'];
  if (route.includes('/rules') || route.includes('/rule-versions')) return [method === 'GET' ? 'contests:read' : 'contests:rules:write'];
  return [method === 'GET' ? 'contests:read' : 'contests:write'];
}

export function registerSpecContestRoutes(app: FastifyInstance, repository: SpecContestRepository, brochureStore:ContestBrochureStore, importService:ContestBrochureImportService, adapter: ContestPrincipalAdapter = new DevelopmentHeaderPrincipalAdapter()): void {
  principalAdapters.set(app, adapter);
  app.get(`${PREFIX}/contests`, async (req: FastifyRequest<{ Querystring: { status?: string;query?:string } }>, reply) => { const who = actor(req, reply); if (who) return repository.listContests(who.tenant, req.query.status,req.query.query); });
  app.post(`${PREFIX}/contests`, { schema: { body: { type: 'object', required: ['code', 'nameKey', 'timezone'], properties: { code: { type: 'string', pattern: '^[A-Za-z0-9_-]{3,40}$' }, nameKey: { type: 'string' }, country: false, timezone: { type: 'string' }, templateVersionId: { type: 'string' } }, additionalProperties: false } } }, async (req, reply) => { const cmd = command(req, reply); if (!cmd) return; const input = req.body as Document; const value = await idempotent(repository, reply, cmd, 'createContest', input, async () => !(await repository.codeAvailable(cmd.actor.tenant, String(input.code))) ? 'CONFLICT' : repository.createContest(cmd.actor, input)); if (value === undefined) return; return value === 'CONFLICT' ? problem(reply, 409, 'CON-4091', 'Contest code is already in use') : reply.status(201).send(value); });
  app.get(`${PREFIX}/contests/overview`, async (req, reply) => { const who = actor(req, reply); if (!who) return; const contests = await repository.listContests(who.tenant); return { metrics: [{ code: 'TOTAL', value: contests.items.length }], attentionItems: [] }; });
  app.get(`${PREFIX}/contests/code-availability`, async (req: FastifyRequest<{ Querystring: { code: string } }>, reply) => { const who = actor(req, reply); if (!who) return; const available = await repository.codeAvailable(who.tenant, req.query.code); return { code: req.query.code, available, ...(!available ? { reasonCode: 'CODE_IN_USE' } : {}) }; });
  app.get(`${PREFIX}/contests/:contestId`, { schema: { params: idParams('contestId') } }, async (req: FastifyRequest<{ Params: { contestId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; return await repository.getContest(who.tenant, req.params.contestId) ?? problem(reply, 404, 'CON-4041', 'Contest not found'); });
  app.delete(`${PREFIX}/contests/:contestId`, { schema:{params:idParams('contestId')} },async(req:FastifyRequest<{Params:{contestId:string}}>,reply)=>{const cmd=command(req,reply,true);if(!cmd)return;const value=await idempotent(repository,reply,cmd,'archiveContest',{contestId:req.params.contestId,revision:cmd.revision},()=>repository.archiveContest(cmd.actor,req.params.contestId,cmd.revision!));if(value===undefined)return;if(value==='MISSING')return problem(reply,404,'CON-4041','Contest not found');if(value==='STALE')return problem(reply,412,'CON-4121','Stale contest revision');if(value==='INVALID')return problem(reply,409,'CON-4092','Only completed or cancelled contests may be archived');return value;});
  app.post(`${PREFIX}/contests/:contestId/versions`, { schema: { params: idParams('contestId'), body: { type: 'object', required: ['baseVersionId', 'changeRationale'], properties: { baseVersionId: { type: 'string' }, changeRationale: { type: 'string', minLength: 1, maxLength: 2000 } }, additionalProperties: false } } }, async (req: FastifyRequest<{ Params: { contestId: string }; Body: { baseVersionId: string; changeRationale: string } }>, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'createContestVersion', { contestId: req.params.contestId, body: req.body }, () => repository.cloneVersion(cmd.actor, req.params.contestId, req.body.baseVersionId, req.body.changeRationale)); if (value === undefined) return; return value ? reply.status(201).send(value) : problem(reply, 404, 'CON-4041', 'Contest version not found'); });
  app.post(`${PREFIX}/contests/:contestId/reactivations`,{schema:{params:idParams('contestId'),body:{type:'object',required:['baseVersionId','changeRationale'],properties:{baseVersionId:{type:'string'},changeRationale:{type:'string',minLength:1,maxLength:2000}},additionalProperties:false}}},async(req:FastifyRequest<{Params:{contestId:string};Body:{baseVersionId:string;changeRationale:string}}>,reply)=>{const cmd=command(req,reply,true);if(!cmd)return;const value=await idempotent(repository,reply,cmd,'reactivateContest',{contestId:req.params.contestId,revision:cmd.revision,body:req.body},()=>repository.reactivateContest(cmd.actor,req.params.contestId,cmd.revision!,req.body.baseVersionId,req.body.changeRationale));if(value===undefined)return;if(value==='MISSING')return problem(reply,404,'CON-4041','Contest or base version not found');if(value==='STALE')return problem(reply,412,'CON-4121','Stale contest revision');if(value==='INVALID')return problem(reply,409,'CON-4092','Only historic contests may be reactivated');reply.header('etag',`"${value.revision}"`);return reply.status(201).send(value);});
  app.get(`${PREFIX}/historic-contests`,async(req:FastifyRequest<{Querystring:{status?:string;query?:string}}>,reply)=>{const who=actor(req,reply);if(who)return repository.listHistoric(who.tenant,req.query.status,req.query.query);});
  app.post(`${PREFIX}/contest-imports`,async(req,reply)=>{const cmd=command(req,reply);if(!cmd)return;let file;try{file=await req.file({limits:{files:1,fileSize:contestBrochureMaxBytes()}});}catch{return problem(reply,413,'CON-4131','Brochure exceeds the configured limit');}if(!file)return problem(reply,400,'CON-4001','PDF file is required');const requestedCode=typeof file.fields.requestedCode==='object'&&file.fields.requestedCode&&'value'in file.fields.requestedCode?String(file.fields.requestedCode.value):undefined;let bytes:Buffer;try{bytes=await file.toBuffer();}catch{return problem(reply,413,'CON-4131','Brochure exceeds the configured limit');}const digest=createHash('sha256').update(bytes).digest('hex');let value;try{value=await idempotent(repository,reply,cmd,'startContestBrochureImport',{sha256:digest,fileName:file.filename,sizeBytes:bytes.length,requestedCode},()=>importService.start(cmd.actor,{bytes,fileName:file.filename,mediaType:file.mimetype},requestedCode));}catch(error){if(error instanceof Error&&error.message==='INVALID_PDF')return problem(reply,415,'CON-4151','Only a valid PDF brochure is accepted');if(error instanceof Error&&error.message==='PDF_TOO_LARGE')return problem(reply,413,'CON-4131','Brochure exceeds the configured limit');throw error;}if(value===undefined)return;reply.header('location',`${PREFIX}/contest-imports/${value.importId}`).header('retry-after','1');return reply.status(202).send(value);});
  app.get(`${PREFIX}/contest-imports/:importId`,{schema:{params:idParams('importId')}},async(req:FastifyRequest<{Params:{importId:string}}>,reply)=>{const who=actor(req,reply);if(!who)return;return await importService.get(who.tenant,req.params.importId)??problem(reply,404,'CON-4041','Contest import not found');});
  app.get(`${PREFIX}/contest-versions/:versionId`, { schema: { params: idParams('versionId') } }, async (req: FastifyRequest<{ Params: { versionId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; const value = await repository.version(who.tenant, req.params.versionId); if (!value) return problem(reply, 404, 'CON-4041', 'Contest version not found'); reply.header('etag', `"${value.revision}"`); return value; });
  app.put(`${PREFIX}/contest-versions/:versionId/brochure`,{schema:{params:idParams('versionId')}},async(req:FastifyRequest<{Params:{versionId:string}}>,reply)=>{const cmd=command(req,reply,true);if(!cmd)return;const file=await req.file({limits:{files:1,fileSize:contestBrochureMaxBytes()}});if(!file)return problem(reply,400,'CON-4001','PDF file is required');let bytes:Buffer;try{bytes=await file.toBuffer();}catch{return problem(reply,413,'CON-4131','Brochure exceeds the configured limit');}if(file.mimetype!=='application/pdf'||!file.filename.toLowerCase().endsWith('.pdf')||bytes.length===0||bytes.subarray(0,5).toString()!=='%PDF-')return problem(reply,422,'CON-4221','Only a valid non-empty PDF brochure is accepted');const sha256=createHash('sha256').update(bytes).digest('hex');const brochureId=`brochure_${createHash('sha256').update(`${cmd.actor.tenant}:${req.params.versionId}:${cmd.key}`).digest('hex').slice(0,40)}`;const value=await idempotent(repository,reply,cmd,'uploadContestBrochure',{versionId:req.params.versionId,revision:cmd.revision,fileName:file.filename,sizeBytes:bytes.length,sha256},async()=>{const stored=await brochureStore.put(cmd.actor.tenant,brochureId,bytes);try{const saved=await repository.saveBrochure(cmd.actor,req.params.versionId,cmd.revision!,{brochureId,fileName:file.filename,sizeBytes:stored.sizeBytes,sha256,objectKey:stored.objectKey});if(typeof saved==='string')await brochureStore.delete(stored.objectKey);return saved;}catch(error){await brochureStore.delete(stored.objectKey);throw error;}});if(value===undefined)return;if(value==='MISSING')return problem(reply,404,'CON-4041','Contest version not found');if(value==='STALE')return problem(reply,412,'CON-4121','Stale contest revision');if(value==='IMMUTABLE')return problem(reply,409,'CON-4092','Only draft versions accept brochure uploads');return reply.status(201).send(value);});
  app.get(`${PREFIX}/contest-versions/:versionId/brochure`,{schema:{params:idParams('versionId')}},async(req:FastifyRequest<{Params:{versionId:string}}>,reply)=>{const who=actor(req,reply);if(!who)return;const record=await repository.brochureRecord(who.tenant,req.params.versionId);if(!record||record.status!=='AVAILABLE')return problem(reply,404,'CON-4041','Contest brochure not found');const object=await brochureStore.get(String(record.objectKey));if(!object)return problem(reply,503,'CON-5031','Brochure object storage is unavailable');reply.header('content-type','application/pdf').header('content-length',object.sizeBytes).header('content-disposition',`inline; filename="${String(record.fileName).replaceAll('"','')}"`).header('etag',String(record.sha256)).header('x-content-type-options','nosniff');return reply.send(object.bytes);});
  app.patch(`${PREFIX}/contest-versions/:versionId`, { schema: { params: idParams('versionId'), body } }, async (req: FastifyRequest<{ Params: { versionId: string }; Body: Document }>, reply) => { const who = actor(req, reply); if (!who) return; const match = /^"?(\d+)"?$/.exec(String(req.headers['if-match'] ?? '')); if (!match) return problem(reply, 412, 'CON-4121', 'If-Match must contain the current revision'); const value = await repository.patchVersion(who, req.params.versionId, Number(match[1]), req.body); if (value === 'MISSING') return problem(reply, 404, 'CON-4041', 'Contest version not found'); if (value === 'STALE') return problem(reply, 412, 'CON-4121', 'Stale contest revision'); if (value === 'IMMUTABLE') return problem(reply, 409, 'CON-4092', 'Only drafts are mutable'); reply.header('etag', `"${value.revision}"`); return value; });
  app.post(`${PREFIX}/contest-versions/:versionId/validate`, { schema: { params: idParams('versionId') } }, async (req: FastifyRequest<{ Params: { versionId: string } }>, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'validateContestVersion', { versionId: req.params.versionId }, async () => { const version = await repository.getVersion(cmd.actor.tenant, req.params.versionId); return version ? repository.validate(version) : undefined; }); return value ?? problem(reply, 404, 'CON-4041', 'Contest version not found'); });
  app.get(`${PREFIX}/contest-versions/:versionId/diff`, { schema: { params: idParams('versionId') } }, async (req: FastifyRequest<{ Params: { versionId: string }; Querystring: { againstVersionId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; const value = await repository.diffVersions(who.tenant, req.params.versionId, req.query.againstVersionId); return value ?? problem(reply, 404, 'CON-4041', 'Contest version not found'); });
  app.post(`${PREFIX}/contest-versions/:versionId/submit`, { schema: { params: idParams('versionId'), body: { type: 'object', required: ['attested', 'changeRationale'], properties: { attested: { const: true }, changeRationale: { type: 'string', minLength: 1 }, validationRunId: { type: 'string' }, simulationRunId: { type: 'string' } }, additionalProperties: false } } }, async (req: FastifyRequest<{ Params: { versionId: string }; Body: Document }>, reply) => { const cmd = command(req, reply, true); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'submitContestVersion', { versionId: req.params.versionId, revision: cmd.revision, body: req.body }, () => repository.submit(cmd.actor, req.params.versionId, cmd.revision!)); if (value === undefined) return; if (value === 'MISSING') return problem(reply, 404, 'CON-4041', 'Contest version not found'); if (value === 'STALE') return problem(reply, 409, 'CON-4092', 'Invalid or stale workflow transition'); if (value === 'INVALID') return problem(reply, 422, 'CON-4221', 'Configuration validation failed'); return reply.status(201).send(value); });
  app.get(`${PREFIX}/approvals`, async (req: FastifyRequest<{ Querystring: { status?: string } }>, reply) => { const who = actor(req, reply); if (who) return repository.approvals(who.tenant, req.query.status); });
  app.get(`${PREFIX}/approvals/:approvalId`, { schema: { params: idParams('approvalId') } }, async (req: FastifyRequest<{ Params: { approvalId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; const value = await repository.approval(who.tenant, req.params.approvalId); if (!value) return problem(reply, 404, 'CON-4041', 'Approval not found'); const { tenant: _, ...wire } = value; return wire; });
  app.post(`${PREFIX}/approvals/:approvalId/decisions`, { schema: { params: idParams('approvalId'), body: { type: 'object', required: ['decision'], properties: { decision: { enum: ['APPROVE', 'RETURN', 'REJECT'] }, comment: { type: 'string', maxLength: 2000 } }, additionalProperties: false } } }, async (req: FastifyRequest<{ Params: { approvalId: string }; Body: { decision: string; comment?: string } }>, reply) => { const cmd = command(req, reply, true); if (!cmd) return; if (req.body.decision === 'RETURN' && !req.body.comment) return problem(reply, 422, 'CON-4221', 'RETURN requires a comment'); const value = await idempotent(repository, reply, cmd, 'decideApproval', { approvalId: req.params.approvalId, revision: cmd.revision, body: req.body }, () => repository.decide(cmd.actor, req.params.approvalId, cmd.revision!, req.body.decision, req.body.comment, cmd.key)); if (value === undefined) return; if (value === 'MISSING') return problem(reply, 404, 'CON-4041', 'Approval not found'); if (value === 'MAKER_CHECKER') return problem(reply, 403, 'CON-4032', 'Submitter cannot decide their own approval'); if (value === 'STALE') return problem(reply, 409, 'CON-4092', 'Invalid or stale workflow transition'); return value; });
  app.post(`${PREFIX}/contest-versions/:versionId/publish`, { schema: { params: idParams('versionId') } }, async (req: FastifyRequest<{ Params: { versionId: string } }>, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'publishContestVersion', { versionId: req.params.versionId }, () => repository.publish(cmd.actor, req.params.versionId)); if (value === undefined) return; if (value === 'MISSING') return problem(reply, 404, 'CON-4041', 'Contest version not found'); if (value === 'INVALID') return problem(reply, 409, 'CON-4092', 'Only approved versions may be published'); return reply.status(202).send(value); });
  app.post(`${PREFIX}/source-snapshots`, { schema: { body } }, async (req, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'registerSourceSnapshot', req.body, () => repository.registerSource(cmd.actor, req.body as Document)); if (value === undefined) return; return value === 'CONFLICT' ? problem(reply, 409, 'CON-4094', 'Source batch checksum conflict') : reply.status(201).send(value); });
  app.post(`${PREFIX}/calculation-runs`, { schema: { body } }, async (req, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'startCalculationRun', req.body, () => repository.startRun(cmd.actor, req.body as Document)); if (value !== undefined) return reply.status(202).send(value); });
  app.get(`${PREFIX}/calculation-runs/:runId`, { schema: { params: idParams('runId') } }, async (req: FastifyRequest<{ Params: { runId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; const value = await repository.run(who.tenant, req.params.runId); if (!value) return problem(reply, 404, 'CON-4041', 'Calculation run not found'); const { tenant: _, requestedBy: __, reasonCode: ___, engineVersion: ____, mappingVersion: _____, ...wire } = value; return wire; });
  app.get(`${PREFIX}/contests/:contestId/agent-results`, { schema: { params: idParams('contestId') } }, async (req: FastifyRequest<{ Params: { contestId: string } }>, reply) => { const who = actor(req, reply); if (who) return repository.results(who.tenant, req.params.contestId); });
  app.get(`${PREFIX}/contests/:contestId/agents/:participantId/result`, { schema: { params: params({ contestId: { type: 'string' }, participantId: { type: 'string' } }, ['contestId', 'participantId']) } }, async (req: FastifyRequest<{ Params: { contestId: string; participantId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; return await repository.results(who.tenant, req.params.contestId, req.params.participantId) ?? problem(reply, 404, 'CON-4041', 'Agent result not found'); });
  app.get(`${PREFIX}/contests/:contestId/agents/:participantId/daily-results`, async (req: FastifyRequest<{ Params: { contestId: string; participantId: string } }>, reply) => { const who = actor(req, reply); if (who) return repository.results(who.tenant, req.params.contestId, req.params.participantId, true); });
  app.post(`${PREFIX}/contest-versions/:versionId/simulations`, { schema: { params: idParams('versionId'), body: { type: 'object', required: ['type', 'versionChecksum'], properties: { type: { enum: ['SAMPLE_PARTICIPANT', 'PORTFOLIO_IMPACT'] }, versionChecksum: { type: 'string', pattern: '^[a-f0-9]{64}$' }, participantId: { type: 'string', minLength: 3, maxLength: 128 }, sourceBusinessDate: { type: 'string', format: 'date' } }, additionalProperties: false } } }, async (req: FastifyRequest<{ Params: { versionId: string }; Body: Document }>, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'startContestSimulation', { versionId: req.params.versionId, body: req.body }, () => repository.startSimulation(cmd.actor, req.params.versionId, req.body)); if (value === undefined) return; if (value === 'CHECKSUM_MISMATCH') return problem(reply, 409, 'CON-4092', 'Version checksum is stale'); return value ? reply.status(202).send(value) : problem(reply, 404, 'CON-4041', 'Contest version not found'); });
  app.get(`${PREFIX}/simulations/:simulationId`, { schema: { params: idParams('simulationId') } }, async (req: FastifyRequest<{ Params: { simulationId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; return await repository.simulation(who.tenant, req.params.simulationId) ?? problem(reply, 404, 'CON-4041', 'Simulation not found'); });
  const assetBody = { type: 'object', required: ['code', 'name', 'categoryCode', 'configuration'], properties: { code: { type: 'string', pattern: '^[A-Za-z0-9_-]{3,40}$' }, name: { type: 'string', minLength: 1, maxLength: 160 }, nameKey: { type: 'string', pattern: '^contest\\.[A-Za-z0-9_.-]+$' }, categoryCode: { enum: ['ELIGIBILITY', 'QUALITY', 'PRODUCTION', 'REWARD', 'GOVERNANCE'] }, configuration: { type: 'object', minProperties: 1 } }, additionalProperties: false } as const;
  app.post(`${PREFIX}/rules`, { schema: { body: assetBody } }, async (req, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'createReusableRule', req.body, () => repository.createAsset(cmd.actor, 'rule', req.body as Document)); if (value === undefined) return; return value === 'CONFLICT' ? problem(reply, 409, 'CON-4091', 'Rule code already exists') : reply.status(201).send(value); });
  app.get(`${PREFIX}/rules`, async (req, reply) => { const who = actor(req, reply); if (who) return repository.assets(who.tenant); });
  app.get(`${PREFIX}/rule-versions/:ruleVersionId`, { schema: { params: idParams('ruleVersionId') } }, async (req: FastifyRequest<{ Params: { ruleVersionId: string } }>, reply) => { const who = actor(req, reply); if (!who) return; const value = await repository.getRuleVersion(who.tenant, req.params.ruleVersionId); if (!value) return problem(reply, 404, 'CON-4041', 'Rule version not found'); reply.header('etag', `"${value.revision}"`); return value; });
  app.patch(`${PREFIX}/rule-versions/:ruleVersionId`, { schema: { params: idParams('ruleVersionId'), body: { type: 'object', required: ['expression', 'options'], properties: { expression: body, options: body }, additionalProperties: false } } }, async (req: FastifyRequest<{ Params: { ruleVersionId: string }; Body: Document }>, reply) => { const cmd = command(req, reply, true); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'patchReusableRuleVersion', { ruleVersionId: req.params.ruleVersionId, revision: cmd.revision, body: req.body }, () => repository.patchRuleVersion(cmd.actor, req.params.ruleVersionId, cmd.revision!, req.body)); if (value === undefined) return; if (value === 'MISSING') return problem(reply, 404, 'CON-4041', 'Rule version not found'); if (value === 'STALE') return problem(reply, 412, 'CON-4121', 'Stale rule revision'); if (value === 'IMMUTABLE') return problem(reply, 409, 'CON-4092', 'Only draft rule versions are mutable'); if (typeof value === 'object' && 'kind' in value && value.kind === 'INVALID') return problem(reply, 422, 'CON-4221', 'Rule validation failed', JSON.stringify(value.report.issues)); reply.header('etag', `"${value.revision}"`); return value; });
  app.post(`${PREFIX}/rule-versions/:ruleVersionId/validate`, { schema: { params: idParams('ruleVersionId'), body: { type: 'object', required: ['expression', 'options'], properties: { expression: body, options: body }, additionalProperties: false } } }, async (req: FastifyRequest<{ Params: { ruleVersionId: string }; Body: Document }>, reply) => { const cmd = command(req, reply); if (!cmd) return; const value = await idempotent(repository, reply, cmd, 'validateReusableRuleVersion', { ruleVersionId: req.params.ruleVersionId, body: req.body }, () => repository.validateRuleVersion(cmd.actor.tenant, req.params.ruleVersionId, req.body)); return value ?? problem(reply, 404, 'CON-4041', 'Rule version not found'); });
  app.get(`${PREFIX}/audit-events`, async (req, reply) => { const who = actor(req, reply); if (who) return repository.auditPage(who.tenant); });
}